version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: municipal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-municipal_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-municipal_password}
      POSTGRES_DB: ${POSTGRES_DB:-municipal_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - municipal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-municipal_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: municipal-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://${POSTGRES_USER:-municipal_user}:${POSTGRES_PASSWORD:-municipal_password}@postgres:5432/${POSTGRES_DB:-municipal_db}?schema=public
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
    networks:
      - municipal-network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: municipal-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - municipal-network

# Volúmenes persistentes
volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local

# Red personalizada
networks:
  municipal-network:
    driver: bridge
