/**
 * Sistema de Permisos Granulares
 * Define qué roles pueden acceder a qué módulos y qué acciones pueden realizar
 */

/**
 * Módulos del sistema
 */
export const MODULES = {
  // Core
  AUTH: 'auth',
  USERS: 'users',
  
  // Estructura Organizacional
  DEPARTMENTS: 'departments',
  POSITIONS: 'positions',
  
  // Proyectos
  PROJECTS: 'projects',
  TASKS: 'tasks',
  
  // Finanzas
  BUDGETS: 'budgets',
  EXPENSES: 'expenses',
  INCOME: 'income',
  
  // RRHH
  EMPLOYEES: 'employees',
  PAYROLL: 'payroll',
  ATTENDANCE: 'attendance',
  
  // Tributario
  TAXES: 'taxes',
  TAX_PAYERS: 'tax_payers',
  
  // Catastro
  PROPERTIES: 'properties',
  CADASTRE: 'cadastre',
  
  // Participación Ciudadana
  PETITIONS: 'petitions',
  COMPLAINTS: 'complaints',
  SUGGESTIONS: 'suggestions',
  
  // Gestión de Flota
  VEHICLES: 'vehicles',
  MAINTENANCE: 'maintenance',
  
  // Inventario de Bienes
  ASSETS: 'assets',
  INVENTORY: 'inventory',
  
  // Gestión Documental
  DOCUMENTS: 'documents',
  ARCHIVES: 'archives',
  
  // Servicios Públicos
  PUBLIC_SERVICES: 'public_services',
  SERVICE_REQUESTS: 'service_requests',
  
  // Dashboards
  DASHBOARDS: 'dashboards',
  REPORTS: 'reports',
};

/**
 * Acciones disponibles en el sistema
 */
export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  APPROVE: 'approve',
  REJECT: 'reject',
  EXPORT: 'export',
  IMPORT: 'import',
  MANAGE: 'manage', // Acciones administrativas completas
};

/**
 * Roles del sistema
 */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DIRECTOR: 'DIRECTOR',
  COORDINADOR: 'COORDINADOR',
  EMPLEADO: 'EMPLEADO',
  CIUDADANO: 'CIUDADANO',
};

/**
 * Matriz de Permisos
 * Define qué acciones puede realizar cada rol en cada módulo
 * 
 * Formato: { [MODULO]: { [ROL]: [ACCIONES] } }
 */
export const PERMISSIONS = {
  // ============================================
  // CORE - Autenticación y Usuarios
  // ============================================
  [MODULES.AUTH]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [ACTIONS.READ, ACTIONS.UPDATE],
  },
  
  [MODULES.USERS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.DIRECTOR]: [ACTIONS.READ],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [], // Sin acceso
  },
  
  // ============================================
  // ESTRUCTURA ORGANIZACIONAL
  // ============================================
  [MODULES.DEPARTMENTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.POSITIONS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // PROYECTOS
  // ============================================
  [MODULES.PROJECTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  [MODULES.TASKS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.DIRECTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // FINANZAS
  // ============================================
  [MODULES.BUDGETS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.EXPENSES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.INCOME]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // RECURSOS HUMANOS
  // ============================================
  [MODULES.EMPLOYEES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.PAYROLL]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.ATTENDANCE]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // TRIBUTARIO
  // ============================================
  [MODULES.TAXES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  [MODULES.TAX_PAYERS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  // ============================================
  // CATASTRO
  // ============================================
  [MODULES.PROPERTIES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  [MODULES.CADASTRE]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  // ============================================
  // PARTICIPACIÓN CIUDADANA
  // ============================================
  [MODULES.PETITIONS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  
  [MODULES.COMPLAINTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  
  [MODULES.SUGGESTIONS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  
  // ============================================
  // GESTIÓN DE FLOTA
  // ============================================
  [MODULES.VEHICLES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.MAINTENANCE]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // INVENTARIO DE BIENES
  // ============================================
  [MODULES.ASSETS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.INVENTORY]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // GESTIÓN DOCUMENTAL
  // ============================================
  [MODULES.DOCUMENTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.CREATE, ACTIONS.READ],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  [MODULES.ARCHIVES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  // ============================================
  // SERVICIOS PÚBLICOS
  // ============================================
  [MODULES.PUBLIC_SERVICES]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [ACTIONS.READ],
  },
  
  [MODULES.SERVICE_REQUESTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.EMPLEADO]: [ACTIONS.READ, ACTIONS.UPDATE],
    [ROLES.CIUDADANO]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  
  // ============================================
  // DASHBOARDS Y REPORTES
  // ============================================
  [MODULES.DASHBOARDS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
  
  [MODULES.REPORTS]: {
    [ROLES.SUPER_ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.ADMIN]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.DIRECTOR]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.COORDINADOR]: [ACTIONS.READ, ACTIONS.EXPORT],
    [ROLES.EMPLEADO]: [ACTIONS.READ],
    [ROLES.CIUDADANO]: [],
  },
};

/**
 * Verifica si un rol tiene permiso para realizar una acción en un módulo
 * @param {string} role - Rol del usuario
 * @param {string} module - Módulo a verificar
 * @param {string} action - Acción a verificar
 * @returns {boolean} true si tiene permiso, false en caso contrario
 */
export const hasPermission = (role, module, action) => {
  // SUPER_ADMIN tiene acceso a todo
  if (role === ROLES.SUPER_ADMIN) {
    return true;
  }
  
  // Verificar si el módulo existe
  if (!PERMISSIONS[module]) {
    console.warn(`Módulo no encontrado en permisos: ${module}`);
    return false;
  }
  
  // Verificar si el rol tiene permisos en el módulo
  const modulePermissions = PERMISSIONS[module][role];
  
  if (!modulePermissions) {
    return false;
  }
  
  // Verificar si el rol tiene la acción específica
  return modulePermissions.includes(action);
};

/**
 * Obtiene todos los permisos de un rol para un módulo
 * @param {string} role - Rol del usuario
 * @param {string} module - Módulo a consultar
 * @returns {Array<string>} Array de acciones permitidas
 */
export const getModulePermissions = (role, module) => {
  if (role === ROLES.SUPER_ADMIN) {
    return Object.values(ACTIONS);
  }
  
  if (!PERMISSIONS[module]) {
    return [];
  }
  
  return PERMISSIONS[module][role] || [];
};

/**
 * Verifica si un rol tiene acceso a un módulo (al menos una acción)
 * @param {string} role - Rol del usuario
 * @param {string} module - Módulo a verificar
 * @returns {boolean} true si tiene acceso, false en caso contrario
 */
export const hasModuleAccess = (role, module) => {
  if (role === ROLES.SUPER_ADMIN) {
    return true;
  }
  
  const permissions = getModulePermissions(role, module);
  return permissions.length > 0;
};

/**
 * Obtiene todos los módulos a los que un rol tiene acceso
 * @param {string} role - Rol del usuario
 * @returns {Array<string>} Array de módulos accesibles
 */
export const getAccessibleModules = (role) => {
  if (role === ROLES.SUPER_ADMIN) {
    return Object.values(MODULES);
  }
  
  return Object.keys(PERMISSIONS).filter(module => {
    const permissions = PERMISSIONS[module][role];
    return permissions && permissions.length > 0;
  });
};
